name: Test Training

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install dependencies
        run: |
          pip install flake8 pytest-cov
          pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: pytest --cov tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
